eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: U3P+xCMTINo83fVjH/NL/QYBuGYWt47CHsskWtAGq5l3VJn60ERERsaziCzziJwLufJ7HUBCpIXI